export const team = [
  {
    id: 7,
    criteria: "HeadCoordinator",
    name: "Ravil Patel",
    phone: "9803043231",
    imgUrl: "/team/RAVIL_MARKETING.jpeg",
    linkedIn: "www.linkedin.com/in/ravil-patel-b65062227",
  },
  {
    id: 1,
    criteria: "HeadCoordinator",
    name: "Abhijeet Jharbadee",
    phone: "8319097205",
    imgUrl: "/team/Abhijeet_Jharbade_Outlook.jpg",
    linkedIn:
      "https://www.linkedin.com/in/abhijeet-jharbade-084992228?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 2,
    criteria: "sponsership",
    name: "Aditya Oza",
    phone: "8866856028",
    imgUrl: "/team/Aditya_Oza_Overall_Coordinator.jpg",
    linkedIn: "https://www.linkedin.com/in/aditya-oza-abcd/",
  },
  {
    id: 3,
    criteria: "HeadCoordinator",
    name: "Aryansh Verma",
    phone: "9617494339",
    imgUrl: "/team/Aryansh_Verma_Overall_Coordinator.jpg",
    linkedIn: "https://www.linkedin.com/in/aryanshverma25",
  },
  {
    id: 4,
    criteria: "marketing",
    name: "Gautam Gupta",
    phone: "9414066706",
    imgUrl: "/team/Gautam_Gupta_Marketing.jpeg",
    linkedIn: "https://www.linkedin.com/in/gautam-gupta-906976261/",
  },
  {
    id: 5,
    criteria: "outlook",
    name: "Jay padia",
    phone: "8956796716",
    imgUrl: "/team/Jay.jpg",
    linkedIn: "https://www.linkedin.com/in/jay-padia/",
  },
  {
    id: 9,
    criteria: "technical",
    name: "Deepesh Agrawal",
    phone: "6268181226",
    imgUrl: "/team/Shivam_Kushwaha_Technical_Events.JPG",
    linkedIn: "https://www.linkedin.com/in/deepesh-agrawal-238601198/",
  },
  // {
  //   id: 9,
  //   criteria: "technical",
  //   name: "Kapil Soni",
  //   phone: "6268181226",
  //   imgUrl: "/team/Shivam_Kushwaha_Technical_Events.JPG",
  //   linkedIn: "https://www.linkedin.com/in/deepesh-agrawal-238601198/",
  // },
  {
    id: 6,
    criteria: "technical",
    name: "priykrit Verma",
    phone: "9109562757",
    imgUrl: "/team/Priykrit_Varma_Technical.jpg",
    linkedIn: "https://www.linkedin.com/in/priykrit-varma-127aa5249/",
  },
  {
    id: 8,
    criteria: "technical",
    name: "shivam kushwaha",
    phone: "9198364979",
    imgUrl: "/team/Shivam_Kushwaha_Technical_Events.JPG",
    linkedIn: "https://www.linkedin.com/in/shivam-kushwaha21",
  },
  {
    id: 10,
    criteria: "marketing",
    name: "Deependra Singh Bhow",
    phone: "6260613425",
    imgUrl: "/team/deep.jpg",
    linkedIn:
      "https://www.linkedin.com/in/deependra-singh-bhow-956864238?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 11,
    criteria: "outlook",
    name: "Aman Kumar",
    phone: "8081338665",
    linkedIn: "https://www.linkedin.com/in/aman-kumar-a402a7229/",
    imgUrl: "/team/deep.jpg",
  },
];

export const culturalEvent = [
  {
    SNO: 1,
    Event: "Photography contest",
    Event_Heads: ["Debashish Padhy", "Akshat Srivatava"],
    Distribution: [
      "1st Prize : ₹3000",
      "2nd Prize : ₹2000",
      "3rd Prize : ₹1000",
      "Banner Standees : ₹500",
      "Flex and other utilities : ₹1000",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Online",
  },
  {
    SNO: 2,
    Event: "Art and Sketching",
    Event_Heads: ["Shalini Singh", "Are Koushik"],
    Distribution: [
      "1st Prize : ₹3000",
      "2nd Prize : ₹2000",
      "3rd Prize : ₹1000",
      "Banner Standees : ₹500",
      "Arena Requirements : ₹500",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Hybrid",
  },
  {
    SNO: 3,
    Event: "Singing Contest (SOLO)",
    Event_Heads: ["Anoushka Koul", "Mohd.Kaif"],
    Distribution: [
      "1st Prize : ₹5000",
      "2nd Prize : ₹3000",
      "3rd Prize : ₹2000",
      "Banner Standees : ₹1000",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Offline",
  },
  {
    SNO: 4,
    Event: "Singing Contest (DUET)",
    Event_Heads: ["Anoushka Koul", "Mohd.Kaif"],
    Distribution: [
      "1st Prize : ₹7000",
      "2nd Prize : ₹5000",
      "3rd Prize : ₹3000",
      "Banner Standees : ₹1000",
    ],
    No_of_Team_Mem: [2, null],
    Mode: "Offline",
  },
  {
    SNO: 5,
    Event: "Dance Battle (Solo and Duet)",
    Event_Heads: ["Aryan Kumar Baghel", "Ramarakshith Katta"],
    Distribution: [
      "1st Prize : ₹6000",
      "2nd Prize : ₹4000",
      "3rd Prize : ₹2000",
      "Banner Standees : ₹500",
      "Flex and other utilities : ₹500",
    ],
    No_of_Team_Mem: [1, 2],
    Mode: "Offline",
  },
  {
    SNO: 6,
    Event: "Dance Battle (Group)",
    Event_Heads: ["Aryan Kumar Baghel", "Ramarakshith Katta"],
    Distribution: [
      "1st Prize : ₹7000",
      "2nd Prize : ₹5000",
      "3rd Prize : ₹3000",
      "Banner Standees : ₹500",
      "Flex : ₹1000",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
  },
  {
    SNO: 7,
    Event: "Nukkad Natak Contest",
    Event_Heads: ["Swastika Satya", "Krishna Agrawal"],
    Distribution: [
      "1st Prize : ₹10000",
      "2nd Prize : ₹6000",
      "3rd Prize : ₹4000",
      "Banner Standees : ₹500",
      "Flex : ₹500",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
  },
  {
    SNO: 8,
    Event: "Battle of Bands",
    Event_Heads: ["Priyanshu Srivastava", "Avasarala Nirupam Laxmi Srujan"],
    Distribution: [
      "1st Prize : ₹11000",
      "2nd Prize : ₹7000",
      "3rd Prize : ₹4000",
      "Banner Standees : ₹500",
      "Flex and other req : ₹10000",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
  },
  {
    SNO: 9,
    Event: "Fashion Contest",
    Event__Heads: ["Anjali Daheriya", "Thanisha Dewangan"],
    Distribution: [
      "1st Prize : ₹15000",
      "2nd Prize : ₹10000",
      "3rd Prize : ₹5000",
    ],
    No_of_Team_Mem: [2, null],
    Mode: "Offline",
  },
  {
    SNO: 10,
    Event: "Public Speaking Event",
    Event_Heads: ["Kanika Malhotra", "Shreya Tiwari"],
    Distribution: [
      "1st Prize : ₹8000",
      "2nd Prize : ₹4000",
      "3rd Prize : ₹2000",
    ],
    No_of_Team_Mem: [3, null],
    Mode: "Offline",
  },
];
