export const team = [
  {
    id: 1,
    criteria: "Lead",
    name: "Dr. Satyanarayana Vollala",
    phone: "7712474049",
    about: "Faculty Coordinator",
    imgUrl: "/team/satyanarayana_vollala.jpg",
    linkedIn: "www.linkedin.com/in/satyanarayana-vollala-530833163",
  },
  {
    id: 2,
    criteria: "Lead",
    name: "Aryansh Verma",
    phone: "9617494339",
    about: "Sponsership Head",
    imgUrl: "/team/Aryansh_Verma_Overall_Coordinator.jpg",
    linkedIn: "www.linkedin.com/in/aryanshverma25",
  },
  {
    id: 3,
    criteria: "Lead",
    name: "Jay Padia",
    phone: "8956796716",
    about: "Sponserhip Head",
    imgUrl: "/team/Jay.jpg",
    linkedIn: "www.linkedin.com/in/jay-padia/",
  },
  {
    id: 4,
    criteria: "Lead",
    name: "Ravil Patel",
    phone: "9893043231",
    about: "Marketing Head",
    imgUrl: "/team/RAVIL_MARKETING.jpeg",
    linkedIn: "www.linkedin.com/in/ravil-patel-b65062227",
  },
  {
    id: 5,
    criteria: "Lead",
    name: "Gautam Gupta",
    about: "Mareting Head",
    phone: "9414066706",
    imgUrl: "/team/Gautam_Gupta_Marketing.jpeg",
    linkedIn: "www.linkedin.com/in/gautam-gupta-906976261/",
  },
  {
    id: 6,
    criteria: "Lead",
    name: "Abhijeet Jharbadee",
    phone: "8319097205",
    about: "Outlook Head",
    imgUrl: "/team/Abhijeet_Jharbade_Outlook.jpg",
    linkedIn: "www.linkedin.com/in/abhijeet-jharbade-084992228",
  },
  {
    id: 7,
    criteria: "Lead",
    name: "Deependra Singh Bhow",
    phone: "6260613425",
    about: "Outlook Head",
    imgUrl: "/team/deep.jpg",
    linkedIn: "www.linkedin.com/in/deependra-singh-bhow-956864238",
  },
  {
    id: 8,
    criteria: "Lead",
    name: "Nidhi Bhaskar",
    phone: "8109006158",
    about: "Design Head",
    linkedIn: "www.linkedin.com/in/nidhi-bhaskar-682148229/",
    imgUrl: "/team/NIDHI.jpg",
  },
  {
    id: 9,
    criteria: "Lead",
    name: "Deepesh Agrawal",
    phone: "6268181226",
    about: "Website Head",
    imgUrl: "/team/deepesh_agrawal.jpg",
    linkedIn: "www.linkedin.com/in/deepesh-agrawal-238601198/",
  },
  {
    id: 10,
    criteria: "Lead",
    name: "Kapil Soni",
    phone: "8770554637",
    about: "Website Head",
    imgUrl: "/team/Kapil_soni.jpeg",
    linkedIn: "www.linkedin.com/in/kapil-soni-07b979228",
  },
  {
    id: 11,
    criteria: "Lead",
    name: "Aman Kumar",
    phone: "8081338665",
    about: "Hospitality Head",
    linkedIn: "www.linkedin.com/in/aman-kumar-a402a7229/",
    imgUrl: "/team/aman_kumar.jpeg",
  },
  {
    id: 12,
    criteria: "Lead",
    name: "Aditya Thakur",
    phone: "9131571609",
    about: "Hospitality Head",
    linkedIn: "www.linkedin.com/in/aditya-thakur-828201229/",
    imgUrl: "/team/Aditya_thakur.jpeg",
  },
  {
    id: 13,
    criteria: "Lead",
    name: "Shivam Kushwaha",
    phone: "9198364979",
    about: "Technical Events Head",
    imgUrl: "/team/Shivam_Kushwaha_Technical_Events.JPG",
    linkedIn: "www.linkedin.com/in/shivam-kushwaha21",
  },
  {
    id: 14,
    criteria: "Lead",
    name: "Priykrit Varma",
    phone: "9109562757",
    about: "Technical Events Head",
    imgUrl: "/team/Priykrit_Varma_Technical.jpeg",
    linkedIn: "www.linkedin.com/in/priykrit-varma-127aa5249/",
  },
  {
    id: 15,
    criteria: "Lead",
    name: "Aditya Oza",
    phone: "8866856028",
    about: "Cultural Events Head",
    imgUrl: "/team/Aditya_Oza_Overall_Coordinator.jpg",
    linkedIn: "www.linkedin.com/in/aditya-oza-abcd/",
  },
  {
    id: 16,
    criteria: "Lead",
    name: "Akshat Shree Mishra",
    phone: "6265636412",
    about: "Cultural Events Head",
    linkedIn: "www.linkedin.com/in/akshat-shree-mishra-82a805244",
    imgUrl: "/team/Akshat_Shree_Mishra_Cultural_head.jpg",
  },
  {
    id: 17,
    criteria: "Lead",
    name: "Rimjhim",
    phone: "9839676977",
    about: "Cultural Events Head",
    linkedIn: "www.linkedin.com/in/rimjhim-sharma-966b38257/",
    imgUrl: "/team/Rimjhim_CulturalHead.jpg",
  },
  {
    id: 18,
    criteria: "Lead",
    name: "Suyash Gupta",
    phone: "9178993199",
    about: "Sports Events Head",
    linkedIn: "www.linkedin.com/in/suyash-gupta-067861234/?/",
    imgUrl: "/team/Suyash_69_Sports_Head.png",
  },
  {
    id: 19,
    criteria: "Lead",
    name: "Yash",
    phone: "6203763329",
    about: "Sports Events Head",
    linkedIn: "www.linkedin.com/in/yash-raj-164222290/",
    imgUrl: "/team/Yash_Sports.jpg",
  },
  {
    id: 20,
    criteria: "Lead",
    name: "Apurva Sahu ",
    phone: "8081338665",
    about: "VideoEditing Team Head",
    linkedIn: "www.linkedin.com/in/apurva-sahu-a4481425a/",
    imgUrl: "/team/Apurva_Video.jpg",
  },
  {
    id: 21,
    criteria: "Lead",
    name: "Kanika Malhotra ",
    phone: "8809374054",
    about: "Content Team Head",
    linkedIn: "www.linkedin.com/in/kanika-malhotra-852956256/?",
    imgUrl: "/team/Kanika Malhotra_Content Lead.jpg",
  },
  {
    id: 22,
    criteria: "Lead",
    name: "Tanvi Kori",
    phone: "6261200465",
    about: "Content Head",
    linkedIn: "www.linkedin.com/in/tanvi-k-893516264/",
    imgUrl: "/team/Tanvi.jpg",
  },
];

export const culturalEvent = [
  {
    SNO: 1,
    Event: "Photography contest",
    Event_Heads: [
      "Debashish Padhy - 8374344812",
      "Akshat Srivatava - 7016358388",
    ],
    Distribution: [
      "1st Prize : ₹3000",
      "2nd Prize : ₹2000",
      "3rd Prize : ₹1000",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Online",
    imgUrl: "/events/cultural/PC.jpg",
    about:
      "Photographers take photos throughout the technovate and the best one wins",
  },
  {
    SNO: 2,
    Event: "Art and Sketching Event",
    Event_Heads: ["Shalini Singh - 9893018267", "Are Koushik -  8465017840"],
    imgUrl: "/events/cultural/ASM.png",
    Distribution: [
      "1st Prize : ₹3000",
      "2nd Prize : ₹2000",
      "3rd Prize : ₹1000",
      "Banner Standees : ₹500",
      "Arena Requirements : ₹500",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Hybrid",
    about: "...",
  },
  {
    SNO: 3,
    Event: "Singing Contest (SOLO)",
    Event_Heads: ["Anoushka Koul - 8449194200", "Mohd.Kaif - 9727833388"],
    Distribution: [
      "1st Prize : ₹5000",
      "2nd Prize : ₹3000",
      "3rd Prize : ₹2000",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Offline",
    imgUrl: "/events/cultural/Singing.jpg",
    about:
      "Step into the spotlight and let your voice soar in the electrifying world of a singing competition. It's not just about hitting the right notes; it's about capturing hearts and leaving the audience breathless. So grab the mic, hit those high notes, and let the world hear the magic in your soul!",
  },
  {
    SNO: 4,
    Event: "Singing Contest (DUET)",
    Event_Heads: ["Anoushka Koul - 8449194200", "Mohd.Kaif - 9727833388"],
    Distribution: [
      "1st Prize : ₹7000",
      "2nd Prize : ₹5000",
      "3rd Prize : ₹3000",
    ],
    No_of_Team_Mem: [2, null],
    imgUrl: "/events/cultural/Singing.jpg",
    Mode: "Offline",
    about:
      "Get your buddy up for a melodic rollercoaster, forge two voices into one, and make the echoes of duet brilliance linger in the hearts of all who bear witness.",
  },
  {
    SNO: 5,
    Event: "Dance Battle (Solo and Duet)",
    Event_Heads: [
      "Aryan Kumar Baghel - 7000978867",
      "Ramarakshith Katta - 7036422159",
    ],
    Distribution: [
      "1st Prize : ₹6000",
      "2nd Prize : ₹4000",
      "3rd Prize : ₹2000",
    ],
    No_of_Team_Mem: [1, 2],
    imgUrl: "/events/cultural/Dance.jpg",
    Mode: "Offline",
    about: "...",
  },
  {
    SNO: 6,
    Event: "Dance Battle (Group)",
    Event_Heads: [
      "Aryan Kumar Baghel - 7000978867",
      "Ramarakshith Katta - 7036422159",
    ],
    Distribution: [
      "1st Prize : ₹7000",
      "2nd Prize : ₹5000",
      "3rd Prize : ₹3000",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
    imgUrl: "/events/cultural/Dance.jpg",
    about:
      "Get ready to witness electrifying moves and fierce competition at our explosive group dance battle! Feel the heat as teams clash on the dance floor, showcasing their best beats, rhythms, and jaw-dropping choreography. Join us for an adrenaline-packed evening of non-stop entertainment and thrilling showdowns!",
  },
  {
    SNO: 7,
    Event: "Nukkad Natak Contest",
    Event_Heads: ["Swastika Satya", "Krishna Agrawal"],
    Distribution: [
      "1st Prize : ₹10000",
      "2nd Prize : ₹6000",
      "3rd Prize : ₹4000",
    ],
    No_of_Team_Mem: null,
    imgUrl: "/events/cultural/ASM.png",
    Mode: "Offline",
    about: "...",
  },
  {
    SNO: 8,
    Event: "Battle of Bands Event",
    Event_Heads: [
      "Priyanshu Srivastava - 9935062012",
      "Avasarala Nirupam Laxmi - 6309552954",
    ],
    Distribution: [
      "1st Prize : ₹11000",
      "2nd Prize : ₹7000",
      "3rd Prize : ₹4000",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
    imgUrl: "/events/cultural/BOB.jpg",
    about:
      "Get ready for an electrifying musical showdown! Bands from all over the country are set to unleash their talent in a clash of the best. With designated time slots for each, the stage will come alive with captivating performances. Our expert panel of judges is geared up to crown the top three, making it a night of unforgettable musical magic!    ",
  },
  {
    SNO: 9,
    Event: "Fashion Show Contest",
    Event_Heads: [
      "Anjali Daheriya  - 9301465728",
      "Thanisha Dewangan - 6232273027",
    ],
    Distribution: [
      "1st Prize : ₹15000",
      "2nd Prize : ₹10000",
      "3rd Prize : ₹5000",
    ],
    No_of_Team_Mem: [2, null],
    imgUrl: "/events/cultural/FC.jpg",
    Mode: "Offline",
    about:
      "the fashion contest unfolds with a Western flair in round one, followed by an enchanting showcase of Indian tradition in round two, celebrating the fusion of global styles on a single runway",
  },
  {
    SNO: 10,
    Event: "Public Speaking Event",
    Event_Heads: ["Kanika Malhotra - 8809374054", "Shreya Tiwari - 9425511225"],
    Distribution: [
      "1st Prize : ₹8000",
      "2nd Prize : ₹4000",
      "3rd Prize : ₹2000",
    ],
    No_of_Team_Mem: [3, null],
    imgUrl: "/events/cultural/PS.jpg",
    Mode: "Offline",
    about: "...",
  },
];

export const technicalEvent = [
  {
    SNO: 1,
    Event: "Wall Street Waltz",
    imgUrl: "/events/technical/wall street waltz(mobile).png",
    Event_Heads: ["Ravil Patel - 9893043231", "Abhinav Roy - 7974751882"],
    Distribution: ["₹5000"],
    Mode: "Online",
    about:
      'Test your trading mettle in "Wall Street Waltz": a solo virtual stock market competition on StockGro, where the greenest portfolio wins!',
  },
  {
    SNO: 2,
    Event: "Venture Vista",
    Event_Heads: [
      "Ashutosh Jaiswal - 9129093900",
      "Karan Agrawal - 7077183484",
    ],
    Distribution: ["₹10000"],
    Mode: "Offline",
    imgUrl: "/events/technical/venture vista(mobile).png",
    about:
      "In a high-stakes showdown, innovators unleash entrepreneurial skills, battling intense pitches and tackling real-life brand challenges to test their mettle and critical thinking.",
  },
  {
    SNO: 3,
    Event: "SpeedRun",
    Distribution: ["₹10000"],
    Event_Heads: ["Vineet - 9893395818", "Dhyanendra Tripathi - 7355206518"],
    imgUrl: "/events/technical/speedrun(mobile).png",
    Mode: "Offline",
    about:
      "Code at the Speed of Thought: Unleash Your Programming Prowess in the Ultimate Coding Speedrun Challenge!",
  },
  {
    SNO: 4,
    Event: "Robolution",
    Distribution: ["₹40000"],
    Event_Heads: [
      "Lakshya Garg - 9818791666",
      "Bhavesh Gyanchandani - 9834304932",
    ],
    imgUrl: "/events/technical/robolution(mobile).png",
    Mode: "Offline",
    about: "Tech meets tact: simple robots, epic clashes",
  },
  {
    SNO: 5,
    Event: "DataPunk",
    Distribution: ["₹10000"],
    imgUrl: "/events/technical/datapunk(mobile).png",
    Event_Heads: ["Sanskar Singh - 7000486098", "Sanchit Namdeo - 8989846583"],
    Mode: "Online",
    about: "Train, Test, Triumph... Unleash your inner DataPunk !!!",
  },
  {
    SNO: 6,
    Event: "Wired Wizardry",
    Distribution: ["₹10000"],
    imgUrl: "/events/technical/WIRED_mobile.png",
    Event_Heads: ["Ishita Tegar - 8349402003", "Karthik - 7842757138"],
    about: "Wire up your wizardry, let circuits cast the spell of innovation!",
    Mode: "Offline",
  },
  {
    SNO: 7,
    Event: "Hack-o-Harbour",
    Distribution: ["₹34500"],
    imgUrl: "/events/technical/hack-o-harbour_mobile.png",
    Event_Heads: ["Alankrit Sharma - 7376961118", "Vandit Tyagi - 7840073450"],
    about: "Decipher, Develop, Dominate: Hack the Harbour",
    Mode: "Offline",
  },
  {
    SNO: 8,
    Event: "BrainWave",
    Distribution: ["₹8500"],
    imgUrl: "/events/technical/brainwave_mobile.png",
    Event_Heads: ["Ayush Yadav - 8529133411", "Harsh Shrivastava - 9907882155"],
    about: "BrainWave: Where Minds Collide in the Ultimate Quiz Odyssey!",
    Mode: "Offline",
  },

  {
    SNO: 9,
    Event: "Unlock The Technoverse",
    Distribution: ["₹10,000"],
    imgUrl: "/events/technical/CTF_mobile.png",
    Event_Heads: ["Aman Sahu - 95844 84662", "V. Jashwanth - 8919891146"],
    about: "Unlock the Technoverse: Catch The Flag(CTF)",
    Mode: "Online",
  },
  {
    SNO: 10,
    Event: "AlgoSprint",
    imgUrl: "/events/technical/algosprint_mobile.png",
    Distribution: ["₹10,000"],
    Event_Heads: [
      "Shivaibhav Dewangan - 8602237007",
      "Gaurish Ojha - 6394079252",
    ],
    about: "AlgoSprint: Code, Compete, Conquer!",
    Mode: "Offline",
  },
];

export const blogData = [
  {
    imageAlt: "Yash Khare",
    imageHref: "/blog/yash.webp",
    normalDesc:
      "He also said a third word, hectic, which would be true if not for the enjoyment of planning and organising of the Technovate events, which to him was the best aspect . Through his experiences over the years he says, “Go out of your way to contribute as much as possible for the fest and donot limit yourselves to the role , Go beyond!”",
    boldDesc: "Yash had two words for Technovate- Adventurous and exciting.",
    about: [
      "Yash Khare(2017-2021)",
      "Outlook and Design (2018)",
      "Student Coordinator (2019-2020)",
    ],
  },
  {
    imageAlt: "Nitin",
    imageHref: "/blog/nitin.jpg",
    normalDesc:
      "Technovate 2020, had one of the best line ups but also faced the worst of times due to the pandemic which ended in lockdown and cancellation of the fest just after the ‘7 days to go’ poster was revealed. Nitin was at the center, he was the head coordinator and a first hand witness of the hardships that the team went through.",
    boldDesc:
      "“Be confident and overconfident cause you are no longer a student, you are part of technovate.”",
    about: [
      "Nitin Chandra (2017-2021)",
      "Media Marketing (2018)",
      "Student coordinator (2019-2020)",
    ],
  },
];

export const sportsEvent = [
  {
    SNO: 1,
    Event: "Badminton",
    imgUrl: "/events/sports/Badminton.PNG",
    Event_Heads: ["Ravi Vinayak - 9302710832", "Aditya Jha - 8629992740"],
    Distribution: ["₹15000"],
    Mode: "Offline",
    about: "",
  },
  {
    SNO: 2,
    Event: "Basketball",
    imgUrl: "/events/sports/Basket.PNG",
    Event_Heads: [
      "Ravikant Shrinivas - 7694039081",
      "Rahul Meshram - 7646908233",
    ],
    Distribution: ["₹10000"],
    Mode: "Offline",
    about: "",
  },
  {
    SNO: 3,
    Event: "Chess",
    imgUrl: "/events/sports/Chess.PNG",
    Event_Heads: [
      "Shaurya Malhan - 9643856936",
      "Yashraj - 6203763329",
      "Neha Dhruw - 7828213923",
    ],
    Distribution: ["₹3000"],
    Mode: "Offline",
    about: "",
  },
  {
    SNO: 4,
    Event: "Cricket",
    imgUrl: "/events/sports/Cricket.PNG",
    Event_Heads: [
      "Suyash Gupta - 9179893199",
      "Yashraj - 6203763329",
      "Deependra - 6260613425",
    ],
    Distribution: ["₹10000"],
    Mode: "Offline",
    about: "",
  },
  {
    SNO: 5,
    Event: "Table Tennis",
    imgUrl: "/events/sports/TT.PNG",
    Event_Heads: [
      "Aditya Singh - 7866885755",
      "Kusum Patel - 6304446282",
      "Arnav Pandey - 8287305782",
    ],
    Distribution: ["₹6000"],
    Mode: "Offline",
    about: "",
  },
  {
    SNO: 6,
    Event: "VolleyBall",
    imgUrl: "/events/sports/Volley.PNG",
    Event_Heads: [
      "Mayank Chandra - 7879692647",
      "Yashraj - 6203763329",
      "Neha Dhruw - 7828213923",
    ],
    Distribution: ["₹10000"],
    Mode: "Offline",
    about: "",
  },
  {
    SNO: 7,
    Event: "BGMI",
    imgUrl: "/events/sports/BGMI.PNG",
    Event_Heads: ["Apurva - 9752593689", "Ojash - 9359525156"],
    Distribution: ["₹3500"],
    Mode: "Online",
    about: "",
  },
  {
    SNO: 8,
    Event: "Valorant",
    imgUrl: "/events/sports/Valorant.PNG",
    Event_Heads: ["Apurva - 9752593689", "Ojash - 9359525156"],
    Distribution: ["₹5000"],
    Mode: "Online",
    about: "",
  },
];

export const volunteerData = [
  {
    name: "Cultural Events Team",
    data: [
      "Akshat Srivastava",
      "Anjali Daheriya ",
      "Anoushka koul",
      "Are Koushik ",
      "Aryan Kumar Baghel",
      "Debashish Padhy",
      "Kanika Malhotra ",
      "Krishna Agrawal",
      "Mohd Kaif",
      "Priyanshu Srivastava ",
      "Ramarakshit Katta",
      "Shalini ",
      "Shreya Tiwari ",
      "Srujan",
      "Swastika Satya",
      "Thanisha Dewangan ",
    ],
  },
  {
    name: "Marketing, Media and PR Team",
    data: [
      "Alankrit Sharma",
      "Ankitan Kumar",
      "Aryan Kumar Baghel",
      "Khuman Singh Sonwani",
      "Priyanshu Srivastava ",
      "Raj Bhattacharya ",
      "Rithwik Eluri",
      "Shashwati Bhattacharya",
      "Swastika Satya",
      "Adya Pandey ",
      "Alok Mishra ",
      "Anshul Pratap Lakra",
      "Anwita Chakraborty ",
      "Arnav Ticku",
      "Kartik pandey",
      "Keshavee Bisen ",
      "Meenal Patle ",
      "Sayyed Raahim Adnan Ali ",
      "Shashank Mishra",
      "Taran Pal Singh ",
      "Tejas keshwani ",
      "VAISHNAVI SHRIVASTAVA",
    ],
  },
 
  {
    name: "Designing Team",
    data: [
      "Achanta Satya Karthik",
      "Ojash Verma",
      "S.Chandu",
      "Shreyansh",
      "Tanishka Chauhan ",
      "Trisul",
      "Aditya Raj",
      "Adya Pandey",
      "Diya Dhruv",
      "Hritik Routia",
      "Kaushal Ranjan",
      "Meenal Patle",
      "Parth Patel ",
    ],
  },
  {
    name: "Hospitality and Logistics Team",
    data: [
      "Aneesh Narayan Bandaru",
      "Chirra shyamprakash ",
      "Gagan Narang ",
      "Ketan Sahu",
      "MICHAEL EKKA",
      "Pediredla Suman ",
      "Pushpraj  Singh Paikra ",
      "Sagnik Mazumdar",
      "Shashwat Singh",
      "Shubham jain ",
      "Sri Sathvik Chowdary M ",
      "Aditi Joshi",
      "Chetankumar S Majjagi",
      "Himanshu Singh Kothariya",
      "Mubashshir ",
    ],
  },
  { name: "Website Team", data: ["Manu Sai", "Rishabh Malav", "Yash Raj"] },
 
  {
    name: "Outlook Team",
    data: [
      "Aman kumar singh",
      "Anjali Daheriya ",
      "Anshu Kashyap",
      "Are Koushik",
      "Aseem Rai ",
      "B Naveen Kumar",
      "David Fule",
      "Mohd Kaif",
      "NAMITA SHAH",
      "Punith ",
      "Sanjana Sori",
      "Satvik Yadav ",
      "Saurabh Dixit",
      "Shalini ",
      "Shivangi Sahu",
      "Thanisha Dewangan",
      "Vaibhav Vikas Ranjan",
      "Veneela Telli ",
      "Abhinav Nirapure",
      "Ananya rajawat ",
      "Anjali Dugga ",
      "Anushka ekka ",
      "Arnav Pandey ",
      "Ashritha ",
      "Ayush",
      "Dharmendra dhruw ",
      "Khushboo Painkra ",
      "Kritie Omar ",
      "Paridhi Sharma",
      "Parv Patidar ",
      "Shreyas Keshari",
      "Varsha Dhruw",
      "Vatsal Shah",
      "Yogendra",
      "Yugal chandak ",
    ],
  },
  {
    name: "Parternship Team",
    data: [
      "Aniket Pandey",
      "Ashutosh Jaiswal",
      "Panshul Senapati",
      "R. Sai Shivani ",
      "Shreya Tiwari ",
      "Tanvi Kori",
      "Varsha Sri Narla",
      "Kusum Patel",
      "Mehul Agrawal",
      "Priyadarshi Satyakam ",
      "Tanisha Jain ",
      "Thakur Mahima Nuruti",
      "Virat Patel ",
    ],
  },
  {
    name: "Technical Events Team",
    data: [
      "Abhinav Roy",
      "Aman Sahu",
      "Bhavesh Gyanchandani",
      "Gaurish Ojha",
      "Karan Agrawal",
      "Lakshya Garg",
      "Sanchit Namdeo",
      "Sanskar Singh",
      "Shivaibhav Dewangan",
      "V.Jashwanth",
      "Vandit Tyagi",
      "Vineet",
      "Achanta Satya Karthik",
      "Alankrit Sharma",
      "Ashutosh Jaiswal",
      "Ayush Yadav",
      "Ch Swati",
      "Dhyanendra Tripathi",
      "Harsh Shrivastava",
      "Ishita ",
      "Karthik",
    ],
  },
  {
    name: "Video Editing Team",
    data: [
      "Arpit Kumar Sinha ",
      "Lalith Chandra",
      "Aditya Kumar Nayak",
      "Garv Bajaj ",
      "Shubhang Nande",
    ],
  },
  {
    name: "Content Writing Team",
    data: [
      "Anuja Singh Pandaw ",
      "M Karthikeya Prachodhan ",
      "Shreya Tiwari ",
      "Shivanshu Vishwakarma",
    ],
  },
];
