export const team = [
  {
    id: 12,
    criteria: "HeadCoordinator",
    name: "Dr satyanarayana vollala",
    phone: "7712474049",
    about: "overall coordinator",
    imgUrl: "/team/satyanarayana_vollala.jpg",
    linkedIn: "www.linkedin.com/in/",
  },
  {
    id: 7,
    criteria: "HeadCoordinator",
    name: "Ravil Patel",
    phone: "9803043231",
    about: "marketing Head",
    imgUrl: "/team/RAVIL_MARKETING.jpeg",
    linkedIn: "www.linkedin.com/in/ravil-patel-b65062227",
  },
  {
    id: 1,
    criteria: "HeadCoordinator",
    name: "Abhijeet Jharbadee",
    phone: "8319097205",
    about: "outlook Head",
    imgUrl: "/team/Abhijeet_Jharbade_Outlook.jpg",
    linkedIn:
      "https://www.linkedin.com/in/abhijeet-jharbade-084992228?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 2,
    criteria: "sponsership",
    name: "Aditya Oza",
    phone: "8866856028",
    about: "sponsership Team",
    imgUrl: "/team/Aditya_Oza_Overall_Coordinator.jpg",
    linkedIn: "https://www.linkedin.com/in/aditya-oza-abcd/",
  },
  {
    id: 3,
    criteria: "HeadCoordinator",
    name: "Aryansh Verma",
    phone: "9617494339",
    about: "Sponsership Head",
    imgUrl: "/team/Aryansh_Verma_Overall_Coordinator.jpg",
    linkedIn: "https://www.linkedin.com/in/aryanshverma25",
  },
  {
    id: 4,
    criteria: "marketing",
    name: "Gautam Gupta",
    about: "Mareting Team",
    phone: "9414066706",
    imgUrl: "/team/Gautam_Gupta_Marketing.jpeg",
    linkedIn: "https://www.linkedin.com/in/gautam-gupta-906976261/",
  },
  {
    id: 5,
    criteria: "outlook",
    name: "Jay padia",
    phone: "8956796716",
    about: "Outlook Team",
    imgUrl: "/team/Jay.jpg",
    linkedIn: "https://www.linkedin.com/in/jay-padia/",
  },
  {
    id: 9,
    criteria: "HeadCoordinator",
    name: "Deepesh Agrawal",
    phone: "6268181226",
    about: "Website Head",
    imgUrl: "/team/deepesh_agrawal.jpeg",
    linkedIn: "https://www.linkedin.com/in/deepesh-agrawal-238601198/",
  },
  {
    id: 6,
    criteria: "HeadCoordinator",
    name: "priykrit Varma",
    phone: "9109562757",
    about: "Technical Head",
    imgUrl: "/team/Priykrit_Varma_Technical.jpeg",
    linkedIn: "https://www.linkedin.com/in/priykrit-varma-127aa5249/",
  },
  {
    id: 8,
    criteria: "HeadCoordinator",
    name: "shivam kushwaha",
    phone: "9198364979",
    about: "Technical Team",
    imgUrl: "/team/Shivam_Kushwaha_Technical_Events.JPG",
    linkedIn: "https://www.linkedin.com/in/shivam-kushwaha21",
  },
  {
    id: 10,
    criteria: "marketing",
    name: "Deependra Singh Bhow",
    phone: "6260613425",
    about: "Marketing Team",
    imgUrl: "/team/deep.jpg",
    linkedIn:
      "https://www.linkedin.com/in/deependra-singh-bhow-956864238?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 11,
    criteria: "outlook",
    name: "Aman Kumar",
    phone: "8081338665",
    about: "Outlook Team",
    linkedIn: "https://www.linkedin.com/in/aman-kumar-a402a7229/",
    imgUrl: "/team/aman_kumar.png",
  },
];

export const culturalEvent = [
  {
    SNO: 1,
    Event: "Photography contest",
    Event_Heads: [
      "Debashish Padhy - 8374344812",
      "Akshat Srivatava - 7016358388",
    ],
    Distribution: [
      "1st Prize : ₹3000",
      "2nd Prize : ₹2000",
      "3rd Prize : ₹1000",
      "Banner Standees : ₹500",
      "Flex and other utilities : ₹1000",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Online",
    about:
      "Photographers take photos throughout the technovate and the best one wins",
  },
  {
    SNO: 2,
    Event: "Art and Sketching Event",
    Event_Heads: ["Shalini Singh - 9893018267", "Are Koushik -  8465017840"],
    imgUrl: "/events/cultural/ASM.png",
    Distribution: [
      "1st Prize : ₹3000",
      "2nd Prize : ₹2000",
      "3rd Prize : ₹1000",
      "Banner Standees : ₹500",
      "Arena Requirements : ₹500",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Hybrid",
    about: "...",
  },
  {
    SNO: 3,
    Event: "Singing Contest (SOLO)",
    Event_Heads: ["Anoushka Koul - 8449194200", "Mohd.Kaif - 9727833388"],
    Distribution: [
      "1st Prize : ₹5000",
      "2nd Prize : ₹3000",
      "3rd Prize : ₹2000",
      "Banner Standees : ₹1000",
    ],
    No_of_Team_Mem: [1, null],
    Mode: "Offline",
    about:
      "Step into the spotlight and let your voice soar in the electrifying world of a singing competition. It's not just about hitting the right notes; it's about capturing hearts and leaving the audience breathless. So grab the mic, hit those high notes, and let the world hear the magic in your soul!",
  },
  {
    SNO: 4,
    Event: "Singing Contest (DUET)",
    Event_Heads: ["Anoushka Koul - 8449194200", "Mohd.Kaif - 9727833388"],
    Distribution: [
      "1st Prize : ₹7000",
      "2nd Prize : ₹5000",
      "3rd Prize : ₹3000",
      "Banner Standees : ₹1000",
    ],
    No_of_Team_Mem: [2, null],
    Mode: "Offline",
    about:
      "Get your buddy up for a melodic rollercoaster, forge two voices into one, and make the echoes of duet brilliance linger in the hearts of all who bear witness.",
  },
  {
    SNO: 5,
    Event: "Dance Battle (Solo and Duet)",
    Event_Heads: [
      "Aryan Kumar Baghel - 7000978867",
      "Ramarakshith Katta - 7036422159",
    ],
    Distribution: [
      "1st Prize : ₹6000",
      "2nd Prize : ₹4000",
      "3rd Prize : ₹2000",
      "Banner Standees : ₹500",
      "Flex and other utilities : ₹500",
    ],
    No_of_Team_Mem: [1, 2],
    Mode: "Offline",
    about: "...",
  },
  {
    SNO: 6,
    Event: "Dance Battle (Group)",
    Event_Heads: [
      "Aryan Kumar Baghel - 7000978867",
      "Ramarakshith Katta - 7036422159",
    ],
    Distribution: [
      "1st Prize : ₹7000",
      "2nd Prize : ₹5000",
      "3rd Prize : ₹3000",
      "Banner Standees : ₹500",
      "Flex : ₹1000",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
    about:
      "Get ready to witness electrifying moves and fierce competition at our explosive group dance battle! Feel the heat as teams clash on the dance floor, showcasing their best beats, rhythms, and jaw-dropping choreography. Join us for an adrenaline-packed evening of non-stop entertainment and thrilling showdowns!",
  },
  {
    SNO: 7,
    Event: "Nukkad Natak Contest",
    Event_Heads: ["Swastika Satya", "Krishna Agrawal"],
    Distribution: [
      "1st Prize : ₹10000",
      "2nd Prize : ₹6000",
      "3rd Prize : ₹4000",
      "Banner Standees : ₹500",
      "Flex : ₹500",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
    about: "...",
  },
  {
    SNO: 8,
    Event: "Battle of Bands Event",
    Event_Heads: [
      "Priyanshu Srivastava - 9935062012",
      "Avasarala Nirupam Laxmi - 6309552954",
    ],
    Distribution: [
      "1st Prize : ₹11000",
      "2nd Prize : ₹7000",
      "3rd Prize : ₹4000",
      "Banner Standees : ₹500",
      "Flex and other req : ₹10000",
    ],
    No_of_Team_Mem: null,
    Mode: "Offline",
    about:
      "Get ready for an electrifying musical showdown! Bands from all over the country are set to unleash their talent in a clash of the best. With designated time slots for each, the stage will come alive with captivating performances. Our expert panel of judges is geared up to crown the top three, making it a night of unforgettable musical magic!    ",
  },
  {
    SNO: 9,
    Event: "Fashion Show Contest",
    Event_Heads: [
      "Anjali Daheriya  - 9301465728",
      "Thanisha Dewangan - 6232273027",
    ],
    Distribution: [
      "1st Prize : ₹15000",
      "2nd Prize : ₹10000",
      "3rd Prize : ₹5000",
    ],
    No_of_Team_Mem: [2, null],
    Mode: "Offline",
    about:
      "the fashion contest unfolds with a Western flair in round one, followed by an enchanting showcase of Indian tradition in round two, celebrating the fusion of global styles on a single runway",
  },
  {
    SNO: 10,
    Event: "Public Speaking Event",
    Event_Heads: ["Kanika Malhotra - 8809374054", "Shreya Tiwari - 9425511225"],
    Distribution: [
      "1st Prize : ₹8000",
      "2nd Prize : ₹4000",
      "3rd Prize : ₹2000",
    ],
    No_of_Team_Mem: [3, null],
    Mode: "Offline",
    about: "...",
  },
];

export const technicalEvent = [
  {
    SNO: 1,
    Event: "Wall Street Waltz",
    imgUrl: "/events/technical/wall street waltz(mobile).png",
    Event_Heads: ["Ravil Patel - 9893043231", "Abhinav Roy - 7974751882"],
    Distribution: ["₹5000"],
    about:
      'Test your trading mettle in "Wall Street Waltz": a solo virtual stock market competition on StockGro, where the greenest portfolio wins!',
  },
  {
    SNO: 2,
    Event: "Pichathon",
    Event_Heads: [
      "Ashutosh Jaiswal - 9129093900",
      "Karan Agrawal - 7077183484",
    ],
    Distribution: ["₹10000"],
    imgUrl: "/events/technical/venture vista(mobile).png",
    about:
      "In a high-stakes showdown, innovators unleash entrepreneurial skills, battling intense pitches and tackling real-life brand challenges to test their mettle and critical thinking.",
  },
  {
    SNO: 3,
    Event: "SpeedRun",
    Distribution: ["₹10000"],
    Event_Heads: ["Vineet - 9893395818", "Dhyanendra Tripathi - 7355206518"],
    imgUrl: "/events/technical/speedrun(mobile).png",
    about:
      "Code at the Speed of Thought: Unleash Your Programming Prowess in the Ultimate Coding Speedrun Challenge!",
  },
  {
    SNO: 4,
    Event: "Robolution",
    Distribution: ["₹40000"],
    Event_Heads: [
      "Lakshya Garg - 9818791666",
      "Bhavesh Gyanchandani - 9834304932",
    ],
    imgUrl: "/events/technical/robolution(mobile).png",
    about: "Tech meets tact: simple robots, epic clashes",
  },
  {
    SNO: 5,
    Event: "DataPunk",
    Distribution: ["₹10000"],
    imgUrl: "/events/technical/datapunk(mobile).png",
    Event_Heads: ["Sanskar Singh - 7000486098", "Sanchit Namdeo - 8989846583"],
    about: "Train, Test, Triumph... Unleash your inner DataPunk !!!",
  },
  {
    SNO: 6,
    Event: "Wired Wizardry",
    Distribution: ["₹10000"],
    imgUrl: "/events/technical/WIRED_mobile.png",
    Event_Heads: ["Ishita Tegar - 8349402003", "Karthik - 7842757138"],
    about: "Wire up your wizardry, let circuits cast the spell of innovation!",
  },
  {
    SNO: 7,
    Event: "Hack Harbour",
    Distribution: ["₹34500"],
    imgUrl: "/events/technical/hack-o-harbour_mobile.png",
    Event_Heads: ["Alankrit Sharma - 7376961118", "Vandit Tyagi - 7840073450"],
    about: "Decipher, Develop, Dominate: Hack the Harbour",
  },
  {
    SNO: 8,
    Event: "BrainWave",
    Distribution: ["₹8500"],
    imgUrl: "/events/technical/brainwave_mobile.png",
    Event_Heads: ["Ayush Yadav - 8529133411", "Harsh Shrivastava - 9907882155"],
    about: "BrainWave: Where Minds Collide in the Ultimate Quiz Odyssey!",
  },

  {
    SNO: 9,
    Event: "UTT",
    Distribution: ["₹10,000"],
    imgUrl: "/events/technical/CTF_mobile.png",
    Event_Heads: ["Aman Sahu - 95844 84662", "V. Jashwanth - 8919891146"],
    about: "Unlock the Technoverse: Catch The Flag(CTF)",
  },
  {
    SNO: 10,
    Event: "AlgoSprint",
    imgUrl: "/events/technical/algosprint_mobile.png",
    Distribution: ["₹10,000"],
    Event_Heads: [
      "Shivaibhav Dewangan - 8602237007",
      "Gaurish Ojha - 6394079252",
    ],
    about: "AlgoSprint: Code, Compete, Conquer!",
  },
];

export const blogData = [
  {
    imageAlt: "Yash Khare",
    imageHref: "/blog/yash.webp",
    normalDesc:
      "He also said a third word, hectic, which would be true if not for the enjoyment of planning and organising of the Technovate events, which to him was the best aspect . Through his experiences over the years he says, “Go out of your way to contribute as much as possible for the fest and donot limit yourselves to the role , Go beyond!”",
    boldDesc: "Yash had two words for Technovate- Adventurous and exciting.",
    about: [
      "Yash Khare(2017-2021)",
      "Outlook and Design (2018)",
      "Student Coordinator (2019-2020)",
    ],
  },
  {
    imageAlt: "Nitin",
    imageHref: "/blog/nitin.jpg",
    normalDesc:
      "Technovate 2020, had one of the best line ups but also faced the worst of times due to the pandemic which ended in lockdown and cancellation of the fest just after the ‘7 days to go’ poster was revealed. Nitin was at the center, he was the head coordinator and a first hand witness of the hardships that the team went through.",
    boldDesc:
      "“Be confident and overconfident cause you are no longer a student, you are part of technovate.”",
    about: [
      "Nitin Chandra (2017-2021)",
      "Media Marketing (2018)",
      "Student coordinator (2019-2020)",
    ],
  },
];
